# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: counter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcounter.proto\x12\x07\x63ounter\"6\n\x0e\x43ounterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x12\n\nnext_score\x18\x02 \x01(\x05\"K\n\x0f\x43ounterResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x15\n\rcurrent_score\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'counter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COUNTERREQUEST._serialized_start=26
  _COUNTERREQUEST._serialized_end=80
  _COUNTERRESPONSE._serialized_start=82
  _COUNTERRESPONSE._serialized_end=157
# @@protoc_insertion_point(module_scope)
